import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import NextAuthProvider from '@/containers/next-auth-provider'

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
    title: 'Netflix Clone',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={cn('min-h-screen font-sans antialiased', fontSans.variable)}>
                <NextAuthProvider>{children}</NextAuthProvider>
            </body>
        </html>
    )
}
